//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaweiHMSInstaller.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuaweiHMSInstaller.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Install Page.
        /// </summary>
        internal static string back_to_install_page {
            get {
                return ResourceManager.GetString("back_to_install_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye Bye.
        /// </summary>
        internal static string bye_bye {
            get {
                return ResourceManager.GetString("bye_bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Game.
        /// </summary>
        internal static string change_game {
            get {
                return ResourceManager.GetString("change_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Internet.
        /// </summary>
        internal static string check_internet {
            get {
                return ResourceManager.GetString("check_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking your internet connection.
        /// </summary>
        internal static string check_internet_connection {
            get {
                return ResourceManager.GetString("check_internet_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the ADB Driver.
        /// </summary>
        internal static string downloading_adb_driver {
            get {
                return ResourceManager.GetString("downloading_adb_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &amp; Installing.
        /// </summary>
        internal static string downloading_and_installing {
            get {
                return ResourceManager.GetString("downloading_and_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the HMS AppGallery.
        /// </summary>
        internal static string downloading_appgallery {
            get {
                return ResourceManager.GetString("downloading_appgallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Game.
        /// </summary>
        internal static string downloading_game {
            get {
                return ResourceManager.GetString("downloading_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the HMS Core.
        /// </summary>
        internal static string downloading_hms_core {
            get {
                return ResourceManager.GetString("downloading_hms_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device(Emulator) configuration is in progress.
        /// </summary>
        internal static string emulator_config_progress {
            get {
                return ResourceManager.GetString("emulator_config_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect your device or emulator and try again.
        /// </summary>
        internal static string emulator_try_again_connect {
            get {
                return ResourceManager.GetString("emulator_try_again_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing.
        /// </summary>
        internal static string finishing {
            get {
                return ResourceManager.GetString("finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huawei Mobile Service.
        /// </summary>
        internal static string hms {
            get {
                return ResourceManager.GetString("hms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huawei Mobile Services (HMS) is a suite of mobile services developed by Huawei for its smartphones and other devices..
        /// </summary>
        internal static string hms_info_message_1 {
            get {
                return ResourceManager.GetString("hms_info_message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMS is available in over 170 countries and regions, and it is used by over 700 million users worldwide..
        /// </summary>
        internal static string hms_info_message_2 {
            get {
                return ResourceManager.GetString("hms_info_message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huawei is constantly expanding the HMS ecosystem, and it is working to bring new and innovative services to its users..
        /// </summary>
        internal static string hms_info_message_3 {
            get {
                return ResourceManager.GetString("hms_info_message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMS is designed to be a secure and reliable alternative to Google Mobile Services (GMS), which is the suite of mobile services that is used by most Android smartphones..
        /// </summary>
        internal static string hms_info_message_4 {
            get {
                return ResourceManager.GetString("hms_info_message_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMS includes a variety of services, such as the AppGallery app store, the Huawei Cloud cloud storage service, and the Huawei Health fitness tracking service..
        /// </summary>
        internal static string hms_info_message_5 {
            get {
                return ResourceManager.GetString("hms_info_message_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is a tool that allows you to install and run Android game on the emulator along with Huawei Mobile Services (HMS) apps. The game run depending on Appgallery..
        /// </summary>
        internal static string huawei_emulator_description {
            get {
                return ResourceManager.GetString("huawei_emulator_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huawei Emulator Installer.
        /// </summary>
        internal static string huawei_emulator_installer {
            get {
                return ResourceManager.GetString("huawei_emulator_installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huawei server unreachable at the moment, please try again later..
        /// </summary>
        internal static string huawei_server_unreachable {
            get {
                return ResourceManager.GetString("huawei_server_unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the ADB Driver.
        /// </summary>
        internal static string installing_adb_driver {
            get {
                return ResourceManager.GetString("installing_adb_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the HMS AppGallery.
        /// </summary>
        internal static string installing_appgallery {
            get {
                return ResourceManager.GetString("installing_appgallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Game.
        /// </summary>
        internal static string installing_game {
            get {
                return ResourceManager.GetString("installing_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing HMS Core.
        /// </summary>
        internal static string installing_hms_core {
            get {
                return ResourceManager.GetString("installing_hms_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong with your internet connection, please fix it and try again..
        /// </summary>
        internal static string internet_connection_error {
            get {
                return ResourceManager.GetString("internet_connection_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection NOT OK. Please try again.
        /// </summary>
        internal static string internet_connection_not_ok {
            get {
                return ResourceManager.GetString("internet_connection_not_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection OK.
        /// </summary>
        internal static string internet_connection_ok {
            get {
                return ResourceManager.GetString("internet_connection_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong with your internet connection, reconnecting.
        /// </summary>
        internal static string internet_error_reconnect {
            get {
                return ResourceManager.GetString("internet_error_reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results found.
        /// </summary>
        internal static string no_search_result_found {
            get {
                return ResourceManager.GetString("no_search_result_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input search keyword.
        /// </summary>
        internal static string please_input_seach_keyword {
            get {
                return ResourceManager.GetString("please_input_seach_keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string retry {
            get {
                return ResourceManager.GetString("retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Games.
        /// </summary>
        internal static string search_games {
            get {
                return ResourceManager.GetString("search_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        internal static string step_1 {
            get {
                return ResourceManager.GetString("step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        internal static string step_2 {
            get {
                return ResourceManager.GetString("step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for choosing us.
        /// </summary>
        internal static string thank_you_choosing_us {
            get {
                return ResourceManager.GetString("thank_you_choosing_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for the Installing.
        /// </summary>
        internal static string thanks_for_installing {
            get {
                return ResourceManager.GetString("thanks_for_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        internal static string welcome_to {
            get {
                return ResourceManager.GetString("welcome_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected.
        /// </summary>
        internal static string you_selected {
            get {
                return ResourceManager.GetString("you_selected", resourceCulture);
            }
        }
    }
}
