name: .NET MAUI CI for Windows

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  APTABASE_KEY: ${{ secrets.APTABASE_KEY }} # Aptabase Key

jobs:
# MAUI Windows Build
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Update appsettings.json
        run: |
          $pathToJson = "./src/appsettings.json"
          $jsonContent = Get-Content -Path $pathToJson -Raw | ConvertFrom-Json
          $jsonContent.Settings.SponsorGameAppId = "${{ vars.GAME_ID }}"
          $jsonContent.Settings.YoutuberChanneName = "${{ vars.YOUTUBE_CHANNEL }}"
          $jsonContent.Settings.AptabaseKey = "$env:APTABASE_KEY"
          $jsonContent | ConvertTo-Json -Depth 100 | Set-Content -Path $pathToJson
          $jsonContent
        shell: pwsh
      
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore HuaweiHMSInstaller.sln /p:TargetFramework=net8.0-windows10.0.19041.0 /p:configuration=release 
        
      - name: Build
        run: dotnet build src/HuaweiHMSInstaller.csproj /p:TargetFramework=net8.0-windows10.0.19041.0 /p:configuration=release --no-restore

      - name: Publish for Windows
        run: dotnet publish src/HuaweiHMSInstaller.csproj /p:TargetFramework=net8.0-windows10.0.19041.0 /p:WindowsPackageType=MSIX -c Release -o ./publish/windows

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app-installer
          path: ./src/bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/HuaweiHMSInstaller_0.0.1.0_Test/**